# Generated by Django 4.2.7 on 2023-11-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='carlist',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
