# Generated by Django 4.2.7 on 2023-11-19 04:35

import CarData.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarData', '0002_carlist_price_carlist_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroomlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='carlist',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[CarData.models.alphanumeric]),
        ),
    ]
