# Generated by Django 4.2.7 on 2023-11-19 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarData', '0003_showroomlist_alter_carlist_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='showroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Showrooms', to='CarData.showroomlist'),
            preserve_default=False,
        ),
    ]
